### ISSUE TITLE
Unexpected limitation with Karabiner

### ISSUE THREAD

**Issue by codeanpeace** [evantravers/Hyper.spoon#1]
So first off, I enjoyed your article and really like the idea of Hammerspoon as the translation/automation layer. That said, leveraging unused function keys seems to have a downside.

Context: I've long used my caps lock as escape if pressed alone and hyper or control as modifier otherwise via Karabiner. While Karabiner allows you to suppress sending the modifier with `"lazy": true` when key is pressed along, it doesn't work with non-modifiers like function keys. For example, hitting caps lock once for escape sends both escape and function key keycodes whereas with traditional hyper the modifiers are suppressed and only escape sent as discovered via Karabiner EventViewer.

This means that for those of us who use vim extensively, random characters get inserted that behave oddly. In my case, the f20 key press sent by Karabiner results in a ^P.
<img width="188" alt="image" src="https://user-images.githubusercontent.com/2991389/153344979-7bd35415-364e-4d24-861d-f3c7e7006349.png">

Open to suggestions for thoughts and workarounds! 

ps feel free to close this as it seems more of a Karabiner limitation, but figured I'd share as it does affect the usability unexpectedly

**Comment by codeanpeace** [comment]
Oh hey kindred spirit! 👋 

Hahah, don't remind me – I may have too many tabs open dedicated to ergo, ortholinear, staggered, tenting, DIY programmable keyboards at the moment. I switched from a mechanical das keyboard to a more ergonomic microsoft sculpt ages ago and was recently pleasantly surprised to discover that the ergonomic mechanical keyboard offerings have truly blossomed in the meantime.

Out of curiosity, does QMK or ZMK handle things like vim mode (s+hjkl) or mouse mode (d+hjkl moves cursor)? I've extended that functionality to move windows around (w+hjkl) among other things. I know it has layers, but haven't seen them used with character keys versus modifier keys. I make heavy use of send this key code if pressed alone otherwise do something else fun pretty heavily as you can probably tell. I've found that the caps lock to control when not pressed alone is super helpful for tmux especially and am thinking of putting the hyper key on tab instead.

> `Hyper:bindHotKeys({hyperKey = {{"cmd", "alt", "ctrl", "shift"}, ["§"}})`

Nice, makes sense!
Would no weird character be empty array then? e.g. `{{"cmd", "alt", "ctrl", "shift"}, []}`

> At this point… all I really use karabiner for is disabling the onboard keyboard when I plug in an external. :P
Hahah, how do you work on the go? Is the context/muscle memory switching difficult? That's my biggest concern to a radically different external ergo keyboard layout. The 40% like the Kyria, Corne, Dactyl-Manuform are ones I've been eying... 👀

**Comment by evantravers** [comment]
Oh yes. Typing on a 3x5_3 Corne-ish Zen at the moment: https://lowprokb.ca/

> does QMK or ZMK handle things like…

Yes. You absolutely can implement arrows under `hjkl`… that's how [my layout works](https://evantravers.com/articles/2020/09/02/follow-up-customizing-a-keyboard-layout/#all-together-now) right now. There is support for mouse keys in QMK, and coming soon to ZMK too.

> be empty array then

Maaaaybe… except Lua doesn't have arrays, only tables. It's a weird language. `table[key]` is a syntax for accessing key in table.

> how do you work on the go?

I carry keyboards with me. :P The muscle memory isn't bad. I don't have a problem with it. I've had the Kyria, Corne, not the Dactyl yet.

Feel free to [email](https://evantravers.com/contact/) me if you have more keyboard questions! I may close this.
