### ISSUE TITLE
Distribute as directory ending in .spoon

### ISSUE THREAD

**Issue by lukas-mertens** [evantravers/Hyper.spoon#2]
Hey, 

thanks for your effort! This is going to be the first spoon I use, so i stumbled over a small thing you could optimize for usability: The .zip you are Releasing doesn't contain a directory ending with .spoon, so that you can immediately install it by double-clicking it. As a new user of spoons I had to go to https://github.com/Hammerspoon/hammerspoon/blob/master/SPOONS.md#how-do-i-create-a-spoon to learn how to install it. The fix was to just rename the unpacked directory to Hyper.spoon. Nothing big, just a small convenience-step for new users ;)

**Comment by evantravers** [comment]
Thank you so much!
